#AUGMENTATION: True
#IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
#BATCH_SIZE: 16
#INCLUDE_TOP: False
#EPOCHS: 1
#CLASSES: 2
#WEIGHTS: imagenet
#LEARNING_RATE: 0.01


AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 16 # Use 16 if 32 gives you memory errors, otherwise 32 is fine
INCLUDE_TOP: False
EPOCHS: 10             # Give the model enough time to learn
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.001  # CRUCIAL: A small learning rate for fine-tuning